# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  

source_data_url: https://drive.google.com/u/0/uc?id=13A0RtvZZanHXKZNbz5JKwjjO2FedNQCR&export=download&confirm=t&uuid=f043ebb3-989e-4c7c-8b72-8fcc6538e718&at=AB6BwCAXcsBJw18MGYQb6qmkEqO8:1697168871394

source_download_dirs:
  data_dir : data
  data_file : data.xml


